version: '2'
services:
    portal-app:
        image: portal
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://portal-mysql:3306/portal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 18080:18080
    portal-mysql:
        extends:
            file: mysql.yml
            service: portal-mysql
